services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  cache.aimeos:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['aimeos']

  Aimeos\Aimeos\:
    resource: '../Classes/*'

  Aimeos\Aimeos\Setup:
    tags:
      - name: event.listener
        identifier: 'aimeosSetup'
        method: setupEvent
        event: TYPO3\CMS\Core\Package\Event\AfterPackageActivationEvent
      - name: event.listener
        identifier: 'aimeosSchema'
        method: schemaEvent
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent
      - name: 'install.upgradewizard'

  Aimeos\Aimeos\Upgrade\CTypeMigrationWizard:
    tags:
      - name: 'install.upgradewizard'

  Aimeos\Aimeos\Command\JobsCommand:
    tags:
      - name: 'console.command'
        command: 'aimeos:jobs'
        description: 'Execute Aimeos job controllers'

  Aimeos\Aimeos\Command\SetupCommand:
    tags:
      - name: 'console.command'
        command: 'aimeos:setup'
        description: 'Creates or updates the database tables'

#  dashboard.widget.latestorders:
#    class: 'Aimeos\Aimeos\Widgets\LatestOrdersWidget'
#    tags:
#      - name: dashboard.widget
#        identifier: 'aimeos-latestorders'
#        groupNames: 'general'
#        title: 'LLL:EXT:aimeos/Resources/Private/Language/extension.xlf:widgets.dashboard.latestorder.title'
#        description: 'LLL:EXT:aimeos/Resources/Private/Language/extension.xlf:widgets.dashboard.latestorder.description'
#        iconIdentifier: 'aimeos-widget-latestorders'
#        height: 'medium'
#        width: 'medium'